mediamartdw:

  target: fabric-sql

  outputs:
    fabric-sql:
      type: sqlserver
      driver: ODBC Driver 18 for SQL Server
      host: evxidzw3ig3uxmngewtrq53prq-55c62v3ww43uvd6ubwxecdlbze.database.fabric.microsoft.com
      port: 1433
      database: mediamart_sql-fe7666fb-74f5-469e-b21c-69f05ba3dfca
      schema: dbo
      threads: 1
      authentication: CLI

