mediamartdw:

  target: dev

  outputs:
    dev:
      type: sqlserver
      driver: ODBC Driver 18 for SQL Server
      host: localhost
      port: 1433
      user: dbt
      password: Diana.Nelson
      database: MediaMartDW
      schema: dbo
      encrypt: false
      threads: 1

