version: 2

models:
  - name: Clientes
    description: "Vista final de clientes"
    columns:
      - name: ID_Cliente
        description: "Identificador del cliente"
        data_tests:
          - unique
          - not_null        

      - name: Cliente
        description: "Nombre del cliente"
        data_tests:
          - not_null        

      - name: Edad
        description: "Edad del cliente"

  - name: Productos
    description: "Vista final de productos"
    columns:
      - name: ID_Producto
        description: "Identificador del producto"
        data_tests:
          - unique
          - not_null        

      - name: Producto
        description: "Nombre del producto"
      - name: Precio
        description: "Precio del producto"
      - name: Subcategoria
        description: "Subcategoría del producto"
      - name: Categoria
        description: "Categoría del producto"

  - name: Vendedores
    description: "Vista final de vendedores"
    columns:
      - name: ID_Vendedor
        description: "Identificador del vendedor"
        data_tests:
          - unique
          - not_null        

      - name: Vendedor
        description: "Nombre del vendedor"
      - name: Foto
        description: "URL de la foto del vendedor"
      - name: Territorio
        description: "Territorio asignado al vendedor"

  - name: Tiendas
    description: "Vista final de tiendas"
    columns:
      - name: ID_Tienda
        description: "Identificador de la tienda"
        data_tests:
          - unique
          - not_null        

      - name: Tienda
        description: "Nombre de la tienda"
      - name: CCAA
        description: "Comunidad Autónoma de la tienda"
      - name: Provincia
        description: "Provincia donde se encuentra la tienda"
      - name: Municipio
        description: "Municipio donde se encuentra la tienda"

  - name: Ventas
    description: "Vista final de ventas"
    columns:
      - name: Fecha_Pedido
        description: "Fecha del pedido"
        data_tests:
          - not_null        

      - name: Fecha_Envio
        description: "Fecha de envío"
      - name: Fecha_Factura
        description: "Fecha de facturación"
      - name: ID_Producto
        description: "Identificador del producto vendido"
        data_tests:
          - relationships:
              to: ref('Productos')
              field: ID_Producto

      - name: ID_Cliente
        description: "Identificador del cliente"
        data_tests:
          - relationships:
              to: ref('Clientes')
              field: ID_Cliente
      - name: ID_Tienda
        description: "Identificador de la tienda"
        data_tests:
          - relationships:
              to: ref('Tiendas')
              field: ID_Tienda

      - name: ID_Vendedor
        description: "Identificador del vendedor"
        data_tests:
          - relationships:
              to: ref('Vendedores')
              field: ID_Vendedor

      - name: Precio_Unitario
        description: "Precio unitario del producto"
      - name: Coste_Unitario
        description: "Coste unitario del producto"
      - name: Cantidad
        description: "Cantidad vendida"
        data_tests:
          - not_null        

